### ISSUE TITLE
Deny and Permit decisions should be generic

### ISSUE THREAD

**Issue by msmock** [IHE/ITI.SeR#26]
Section 3.79.4.2.3 Expected Actions defines the enforcement rules of Access Decisions for the Retrieve Document Set Authorization Decision only. 

The enforcement rules shall be generic and moved to the parent section (3.79.4.2.3 Expected Actions)

**Comment by msmock** [comment]
fixed in branch #26

**Comment by unixoid** [comment]
I propose to close this issue as "won't fix", because it does not seem possible to generalize those rules.  A generalized description would be raising more questions than giving answers, because of
- different semantics of transactions combined with ITI-79 (C,R,U,D)
- possibility of partial success vs. requirement of strong atomicity
- potential dependencies between clinical data items ("if the decision is Permit for item X and Deny for item Y, then...")
- potential presence of local policies, consents, and other "environmental" factors
- etc.

**Comment by unixoid** [comment]
22-Jul-2022: Closed as "won't fix" as proposed.  Section 3.79.4.2.3 to be extended with explanations (s. above) -- @unixoid TODO.
